build:
  image: golang:1.16-buster
  script:
    - go mod download
    - go build -ldflags "-linkmode external -extldflags -static" -o build/app
  artifacts:
    paths:
      - build/

run:
  image: alpine:3
  script:
    - build/app
