build-job:
  image: golang:1.16-buster
  script:
    - go mod download
    - go build -o build/app
  artifacts:
    paths:
      - build

run:
  image: alpine:3
  needs: [build]
  script:
    - ./build/app
