build:
  image: golang:1.16-buster
  script:
    - go mod download
    - CGO_ENABLED=0 go build -o build/app
  artifacts:
    paths:
      - build/

run:
  image: alpine:3
  needs: [build]
  script:
    - build/app
